### ISSUE TITLE
Appveyor - Test 1.0.0

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/digest#4]
@hsbt

I just ran AV on digest, results [here](https://ci.appveyor.com/project/MSP-Greg/digest-oo2ts/build/1).

2.3.3-x64 passed using 1.0.2j
2.4.2-x64 passed using 1.0.2l
trunk-x64 failed using 1.1.0g

Single failure was:
```
  1) Failure:
TestDigest::TestDigestParen#test_race_mixed [C:/projects/digest-oo2ts/test/digest/test_digest.rb:263]:
assert_separately failed with error message
pid 1440 exit 0
| #<Thread:0x000000000277b6e8@-:7 run> terminated with exception (report_on_exception is true):
| -:9:in `block (2 levels) in <main>': undefined method `new' for nil:NilClass (NoMethodError)
```

I won't have a chance to look at for a while...

Thanks for all your work with the bundled & default gems, Greg

**Comment by MSP-Greg** [comment]
See PR #5 for appveyor.yml and test patch

**Comment by hsbt** [comment]
Unfortunately, I have no plan to maintain CI with appveyor.
